### ISSUE TITLE
V5 TO-DO

### ISSUE THREAD

**Issue by lsaa** [lsaa/ddstats-rust#20]
- [ ] cache N last games and save gold splits
- [ ] make new cached data available on ws

needs investigation:
- [ ] allow ddinfo custom spawnsets to be loaded through websocket. Will need a confirmation prompt on the client

**Comment by lsaa** [comment]
[rotisseriechicken](https://github.com/rotisseriechicken) [5 hours ago](https://github.com/lsaa/ddstats-rust/issues/18#issuecomment-1062471283)[](https://github.com/rotisseriechicken)

Saving last N games should allow N to be configurable; probably 75 or 100 by default
Saving last N games should probably have a "Threshhold to Save" time, which is configurable: probably 0 by default but also could be 200 or 450 or something, your call; This way people can ignore failed farms which may "skew" their average times, so they can use the averages for whatever they want, like using it to average their last loop attempts only.
Threshhold, and N games (or just N game averages) should be sent / accessible to DDLIVE and such, like Splits are retrievable, so DDLIVE can display what the Threshhold is, and amount of games are


@[rotisseriechicken](https://github.com/rotisseriechicken)
rotisseriechicken [5 hours ago](https://github.com/lsaa/ddstats-rust/issues/18#issuecomment-1062472411)

Averages and Gold Splits perhaps should be organized or enslaved per Player ID, so other accounts and/or offline-ness doesn't muck the metric
Gold Splits should only save for V3 runs which submit successfully
Gold Splits should be configurable so they can be manually overridden

**Comment by rotisseriechicken** [comment]
Fix DDCL spawnsets which have homing collection "disabled" instantly crashing ddstats-rust on starting a run with that spawnset active

**Comment by rotisseriechicken** [comment]
FOCUS: Create an inline and secure self-update system, which requires the least amount of steps + is easiest for the user
